/**********************************************************************************************************************
 * 
 * Script		: DML_DEPARTAMENTOS
 * Autor		: MIGUEL GOMEZ - <gomezcasas.miguelangel@gmail.com>
 * Fecha		: 14/10/2022
 * Descripcion	: DML PARA INSERTAR DATOS EN LA TABLA DEPARTAMENTOS.
 *
***********************************************************************************************************************/

INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '05', 'ANTIOQUIA', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '08', 'ATLÁNTICO', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '11', 'BOGOTÁ, D.C.', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '13', 'BOLÍVAR', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '15', 'BOYACÁ', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '17', 'CALDAS', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '18', 'CAQUETÁ', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '19', 'CAUCA', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '20', 'CESAR', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '23', 'CÓRDOBA', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '25', 'CUNDINAMARCA', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '27', 'CHOCÓ', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '41', 'HUILA', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '44', 'LA GUAJIRA', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '47', 'MAGDALENA', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '50', 'META', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '52', 'NARIÑO', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '54', 'NORTE DE SANTANDER', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '63', 'QUINDÍO', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '66', 'RISARALDA', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '68', 'SANTANDER', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '70', 'SUCRE', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '73', 'TOLIMA', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '76', 'VALLE DEL CAUCA', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '81', 'ARAUCA', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '85', 'CASANARE', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '86', 'PUTUMAYO', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '88', 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '91', 'AMAZONAS', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '94', 'GUAINÍA', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '95', 'GUAVIARE', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '97', 'VAUPÉS', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');
INSERT INTO DEPARTAMENTOS ( CODIGO, NOMBRE, ACTIVO, USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION) VALUES ( '99', 'VICHADA', 1, 'MIGUEL GOMEZ', '10/10/2020', 'MIGUEL GOMEZ', '10/10/2020');

/
COMMIT;